services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: my-girl-base:latest  # Даем имя образу
  core:
    build:
      context: ./core      # Путь к папке с вашим Dockerfile
      args:                # Теперь аргументы на месте
        - HF_TOKEN=${HF_TOKEN}
    environment:
      - HF_TOKEN=${HF_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./static/results:/app/static/results

  code_former:
    build: ./code_former
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: on-failure
    ports:
      - "8001:8001"